# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('detail_url', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'banner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('nav_id', models.AutoField(primary_key=True, serialize=False)),
                ('nav_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'navigation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('sub_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sub_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubMenu2',
            fields=[
                ('sub_menu2_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sub_menu2',
                'managed': False,
            },
        ),
    ]
